plugins {
	id 'fabric-loom' version '1.13-SNAPSHOT'
	id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

base {
    archivesName = project.archives_base_name
}

version = project.mod_version
group = project.maven_group

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	api "blue.endless:jankson:1.2.3"
	include "blue.endless:jankson:1.2.3"
}

processResources {
    def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
}

jar {
	//baseName = "Jankson"
	from "LICENSE"
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// select the repositories you want to publish to
	repositories {
		def env = System.getenv()
		if (env.MAVEN_URL) {
			maven {
				url = env.MAVEN_URL
				credentials {
					username = env.MAVEN_USERNAME
					password = env.MAVEN_PASSWORD
				}
			}
		}
	}
}
